#!/bin/bash
#
#
#
echo -n "siseta kuu numbrina: "
read kuu
case $kuu in
"1") echo "$kuu on jaanuar";;
"2") echo "$kuu on veebruar";;
"3") echo "$kuu on märts";;
"4") echo "$kuu on aprill";;
"5") echo "$kuu on mai";;
"6") echo "$kuu on juuni";;
"7") echo "$kuu on juuli";;
"8") echo "$kuu on august";;
"9") echo "$kuu on september";;
"10") echo "$kuu on oktoober";;
"11") echo "$kuu on november";;
"12") echo "$kuu on detsember";;
*) echo "$kuu on vigane sisend!!!";;
esac
