#!/bin/bash
#
#tervitus script, nime küsimisega
#
echo  "Sisetqa oma ees- ja perekonnanimi: " #küsimus
read eesnimi perekonnanimi
echo Sinu eesnimi on $eesnimi ja perekonnanimi on $perekonnanimi
#
#
#script end

