#!/bin/bash
#
#
echo  "siseta mitu  rida sümbloeid; "
read a1
echo "sisesta mitu sümbolit reas, "
#
read a2
for (( i=1; i<=$a1; i++ ))  ####outer loop
do echo -n $i 
	for (( j=1 ; j<=$a2; j++ )) ##inner loop
do
echo -n "* "
done 
echo ""
done
